# Пользователи

## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "tarasov3@yandex.ru",
  "name": "Vanya",
  "password": "shining123",
  "type": "basic"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "tarasov@yandex.ru",
  "password": "shining123"
}

###

## Отправить изображение
POST http://localhost:5000/users/667233e90385badd490f8b1f/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< D:\Downloads\q78kobag9eg41.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
