# Предложения

## Получить список предложений
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
###

## Добавить новое предложение
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "2. Duis maximus odio dolor",
  "description": "Sed euismod, tortor id tempor venenatis, felis est luctus leo, et interdum lectus orci eu velit. Morbi et rhoncus diam, non blandit massa. Integer tincidunt purus eu tellus commodo ullamcorper.",
  "city": "Hamburg",
  "previewPhoto": "apartment-03.jpg",
  "photos": ["apartment-01.jpg", "apartment-02.jpg", "apartment-03.jpg", "apartment-04.jpg", "apartment-05.jpg", "apartment-06.jpg"],
  "isPremium": true,
  "housingType": "house",
  "numberOfRooms": 9,
  "numberOfGuests": 7,
  "price": 49999,
  "rating": "2",
  "postDate": "2024-05-15T17:10:54.256Z",
  "isFavorite": false,
  "amenities": ["Breakfast", "Air conditioning", "Washer", "Fridge"],
  "author": "66437ba58cc3a3f37f7e9140",
  "location": {
    "latitude": 48.85669,
    "longitude": 2.351500
  }
}
###

## Получить объявление по идентификатору
GET http://localhost:5000/offers/6671fb9237daa6c850ba0e8e HTTP/1.1
###

## Удалить объявление по идентификатору
DELETE http://localhost:5000/offers/6671fb9237daa6c850ba0e7a HTTP/1.1
###

## Обновить объявление
PATCH http://localhost:5000/offers/6671fb9237daa6c850ba0e7f HTTP/1.1
Content-Type: application/json

{
  "title": "Ночной дозор 3",
  "description": "Проверка обновления",
  "price": 999
}
###
